### ISSUE TITLE
KaraDAV ?

### ISSUE THREAD

**Issue by l4nj1n9** [kd2org/webdav-manager.js#1]
It seems there is an error in the README of the project. It is written that Webdav-manager was tested with KaraDAV server with a link, but:
* the link is dead,
* I googled a bit for KaraDAV and did not find any such thing.

**Comment by bohwaz** [comment]
Thank you, but the project is still private and will be made public next week or something like that :) It is a lightweight WebDAV server compatible with NextCloud and ownCloud client apps :)

**Comment by bohwaz** [comment]
@taophp KaraDAV is now available here: https://github.com/kd2org/karadav :)
