### ISSUE TITLE
nginx-dav-ext-module incompatibility

### ISSUE THREAD

**Issue by jurov** [kd2org/webdav-manager.js#2]
Using nginx/1.21.4 server with [nginx-dav-ext-module](https://github.com/arut/nginx-dav-ext-module) , webdav-manager fails on line

`'mime': !is_dir ? node.querySelector('getcontenttype').textContent : null,
`
because tag d:getcontenttype is missing in the response. Fixed it by commenting above line out.

**Comment by bohwaz** [comment]
Thanks for your report, I fixed it :)
